[[machine]]
name = "ibm5150_64k"
type = "Ibm5150v64K"
rom_set = "ibm5150_81_v1"
speaker = true

overlays = [
    "pcxt_2_360k_floppies",
#    "pcxt_2_serial_ports",
    "us_modelf_keyboard",
#    "game_port",
]

    [machine.memory]
    conventional.size = 0x10000 # 64 KiB
    conventional.wait_states = 0

    # Video cards
    [[machine.video]]
    bus_type = "ISA"
    type = "MDA"
    clock_mode = "Character"
